import { IPartisipanGroup } from "./partisipan-group.interface";
export const dummyPartisipanGroups: IPartisipanGroup[] = [
  {
    title: "Peserta Bootcamp Frontend",
    description: "Grup peserta yang mengikuti pelatihan frontend development.",
    partisipan: [
      {
        id: "FR001",
        nama: "Andi Wijaya",
        email: "andi.wijaya@example.com",
        noTelepon: "081234567001",
        kategori: "Mahasiswa",
        jenisKelamin: "L",
      },
      {
        id: "FR002",
        nama: "Dina Rahmawati",
        email: "dina.rahma@example.com",
        noTelepon: "081234567002",
        kategori: "Siswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Peserta Seminar AI",
    description: "Grup partisipan seminar Artificial Intelligence 2025.",
    partisipan: [
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },

    ],
  },
  {
    title: "Grup Umum Event Nasional",
    description: "Partisipan dari berbagai kalangan untuk event nasional.",
    partisipan: [
      {
        id: "UM001",
        nama: "Gilang Mahendra",
        email: "gilang.mahendra@example.com",
        noTelepon: "081234567005",
        kategori: "Umum",
        jenisKelamin: "L",
      },
      {
        id: "UM002",
        nama: "Hana Nuraini",
        email: "hana.nuraini@example.com",
        noTelepon: "081234567006",
        kategori: "Umum",
        jenisKelamin: "P",
      },
      {
        id: "UM003",
        nama: "Ivan Surya",
        email: "ivan.surya@example.com",
        noTelepon: "081234567007",
        kategori: "Umum",
        jenisKelamin: "L",
      },
    ],
  },
  {
    title: "Peserta Bootcamp Frontend",
    description: "Grup peserta yang mengikuti pelatihan frontend development.",
    partisipan: [
      {
        id: "FR001",
        nama: "Andi Wijaya",
        email: "andi.wijaya@example.com",
        noTelepon: "081234567001",
        kategori: "Mahasiswa",
        jenisKelamin: "L",
      },
      {
        id: "FR002",
        nama: "Dina Rahmawati",
        email: "dina.rahma@example.com",
        noTelepon: "081234567002",
        kategori: "Siswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Peserta Seminar AI",
    description: "Grup partisipan seminar Artificial Intelligence 2025.",
    partisipan: [
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Grup Umum Event Nasional",
    description: "Partisipan dari berbagai kalangan untuk event nasional.",
    partisipan: [
      {
        id: "UM001",
        nama: "Gilang Mahendra",
        email: "gilang.mahendra@example.com",
        noTelepon: "081234567005",
        kategori: "Umum",
        jenisKelamin: "L",
      },
      {
        id: "UM002",
        nama: "Hana Nuraini",
        email: "hana.nuraini@example.com",
        noTelepon: "081234567006",
        kategori: "Umum",
        jenisKelamin: "P",
      },
      {
        id: "UM003",
        nama: "Ivan Surya",
        email: "ivan.surya@example.com",
        noTelepon: "081234567007",
        kategori: "Umum",
        jenisKelamin: "L",
      },
    ],
  },
  {
    title: "Peserta Bootcamp Frontend",
    description: "Grup peserta yang mengikuti pelatihan frontend development.",
    partisipan: [
      {
        id: "FR001",
        nama: "Andi Wijaya",
        email: "andi.wijaya@example.com",
        noTelepon: "081234567001",
        kategori: "Mahasiswa",
        jenisKelamin: "L",
      },
      {
        id: "FR002",
        nama: "Dina Rahmawati",
        email: "dina.rahma@example.com",
        noTelepon: "081234567002",
        kategori: "Siswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Peserta Seminar AI",
    description: "Grup partisipan seminar Artificial Intelligence 2025.",
    partisipan: [
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Grup Umum Event Nasional",
    description: "Partisipan dari berbagai kalangan untuk event nasional.",
    partisipan: [
      {
        id: "UM001",
        nama: "Gilang Mahendra",
        email: "gilang.mahendra@example.com",
        noTelepon: "081234567005",
        kategori: "Umum",
        jenisKelamin: "L",
      },
      {
        id: "UM002",
        nama: "Hana Nuraini",
        email: "hana.nuraini@example.com",
        noTelepon: "081234567006",
        kategori: "Umum",
        jenisKelamin: "P",
      },
      {
        id: "UM003",
        nama: "Ivan Surya",
        email: "ivan.surya@example.com",
        noTelepon: "081234567007",
        kategori: "Umum",
        jenisKelamin: "L",
      },
    ],
  },
  {
    title: "Peserta Bootcamp Frontend",
    description: "Grup peserta yang mengikuti pelatihan frontend development.",
    partisipan: [
      {
        id: "FR001",
        nama: "Andi Wijaya",
        email: "andi.wijaya@example.com",
        noTelepon: "081234567001",
        kategori: "Mahasiswa",
        jenisKelamin: "L",
      },
      {
        id: "FR002",
        nama: "Dina Rahmawati",
        email: "dina.rahma@example.com",
        noTelepon: "081234567002",
        kategori: "Siswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Peserta Seminar AI",
    description: "Grup partisipan seminar Artificial Intelligence 2025.",
    partisipan: [
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Grup Umum Event Nasional",
    description: "Partisipan dari berbagai kalangan untuk event nasional.",
    partisipan: [
      {
        id: "UM001",
        nama: "Gilang Mahendra",
        email: "gilang.mahendra@example.com",
        noTelepon: "081234567005",
        kategori: "Umum",
        jenisKelamin: "L",
      },
      {
        id: "UM002",
        nama: "Hana Nuraini",
        email: "hana.nuraini@example.com",
        noTelepon: "081234567006",
        kategori: "Umum",
        jenisKelamin: "P",
      },
      {
        id: "UM003",
        nama: "Ivan Surya",
        email: "ivan.surya@example.com",
        noTelepon: "081234567007",
        kategori: "Umum",
        jenisKelamin: "L",
      },
    ],
  },
  {
    title: "Peserta Bootcamp Frontend",
    description: "Grup peserta yang mengikuti pelatihan frontend development.",
    partisipan: [
      {
        id: "FR001",
        nama: "Andi Wijaya",
        email: "andi.wijaya@example.com",
        noTelepon: "081234567001",
        kategori: "Mahasiswa",
        jenisKelamin: "L",
      },
      {
        id: "FR002",
        nama: "Dina Rahmawati",
        email: "dina.rahma@example.com",
        noTelepon: "081234567002",
        kategori: "Siswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Peserta Seminar AI",
    description: "Grup partisipan seminar Artificial Intelligence 2025.",
    partisipan: [
      {
        id: "AI001",
        nama: "Eko Prasetyo",
        email: "eko.prasetyo@example.com",
        noTelepon: "081234567003",
        kategori: "Dosen",
        jenisKelamin: "L",
      },
      {
        id: "AI002",
        nama: "Fatimah Zahra",
        email: "fatimah.zahra@example.com",
        noTelepon: "081234567004",
        kategori: "Mahasiswa",
        jenisKelamin: "P",
      },
    ],
  },
  {
    title: "Grup Umum Event Nasional",
    description: "Partisipan dari berbagai kalangan untuk event nasional.",
    partisipan: [
      {
        id: "UM001",
        nama: "Gilang Mahendra",
        email: "gilang.mahendra@example.com",
        noTelepon: "081234567005",
        kategori: "Umum",
        jenisKelamin: "L",
      },
      {
        id: "UM002",
        nama: "Hana Nuraini",
        email: "hana.nuraini@example.com",
        noTelepon: "081234567006",
        kategori: "Umum",
        jenisKelamin: "P",
      },
      {
        id: "UM003",
        nama: "Ivan Surya",
        email: "ivan.surya@example.com",
        noTelepon: "081234567007",
        kategori: "Umum",
        jenisKelamin: "L",
      },
    ],
  },
];

export const dummyPartipanData = [
  {
    id: '1',
    nama: 'Ahmad Ramadhan',
    email: 'ahmad.ramadhan@example.com',
    noTelepon: '081234567890',
    kategori: 'Pelajar',
    jenisKelamin: 'Laki-laki',
  },
  {
    id: '2',
    nama: 'Siti Aisyah',
    email: 'siti.aisyah@example.com',
    noTelepon: '081234567891',
    kategori: 'Umum',
    jenisKelamin: 'Perempuan',
  },
  {
    id: '3',
    nama: 'Budi Santoso',
    email: 'budi.santoso@example.com',
    noTelepon: '081234567892',
    kategori: 'Mahasiswa',
    jenisKelamin: 'Laki-laki',
  },
  {
    id: '4',
    nama: 'Rina Marlina',
    email: 'rina.marlina@example.com',
    noTelepon: '081234567893',
    kategori: 'Umum',
    jenisKelamin: 'Perempuan',
  },
  {
    id: '5',
    nama: 'Joko Widodo',
    email: 'joko.widodo@example.com',
    noTelepon: '081234567894',
    kategori: 'Pelajar',
    jenisKelamin: 'Laki-laki',
  },
  {
    id: '6',
    nama: 'Dewi Lestari',
    email: 'dewi.lestari@example.com',
    noTelepon: '081234567895',
    kategori: 'Mahasiswa',
    jenisKelamin: 'Perempuan',
  },
  {
    id: '7',
    nama: 'Andi Nugroho',
    email: 'andi.nugroho@example.com',
    noTelepon: '081234567896',
    kategori: 'Umum',
    jenisKelamin: 'Laki-laki',
  },
  {
    id: '8',
    nama: 'Fitriani Hasanah',
    email: 'fitriani.hasanah@example.com',
    noTelepon: '081234567897',
    kategori: 'Pelajar',
    jenisKelamin: 'Perempuan',
  },
  {
    id: '9',
    nama: 'Agus Salim',
    email: 'agus.salim@example.com',
    noTelepon: '081234567898',
    kategori: 'Umum',
    jenisKelamin: 'Laki-laki',
  },
  {
    id: '10',
    nama: 'Lia Kurniawati',
    email: 'lia.kurniawati@example.com',
    noTelepon: '081234567899',
    kategori: 'Mahasiswa',
    jenisKelamin: 'Perempuan',
  },
  {
    id: '11',
    nama: 'Yusuf Maulana',
    email: 'yusuf.maulana@example.com',
    noTelepon: '081234567900',
    kategori: 'Pelajar',
    jenisKelamin: 'Laki-laki',
  },
  {
    id: '12',
    nama: 'Nadia Salsabila',
    email: 'nadia.salsabila@example.com',
    noTelepon: '081234567901',
    kategori: 'Umum',
    jenisKelamin: 'Perempuan',
  },
  {
    id: '13',
    nama: 'Fajar Pratama',
    email: 'fajar.pratama@example.com',
    noTelepon: '081234567902',
    kategori: 'Mahasiswa',
    jenisKelamin: 'Laki-laki',
  },
  {
    id: '14',
    nama: 'Mega Utami',
    email: 'mega.utami@example.com',
    noTelepon: '081234567903',
    kategori: 'Pelajar',
    jenisKelamin: 'Perempuan',
  },
  {
    id: '15',
    nama: 'Rizky Hidayat',
    email: 'rizky.hidayat@example.com',
    noTelepon: '081234567904',
    kategori: 'Umum',
    jenisKelamin: 'Laki-laki',
  },
]