import { IStaff } from "./staff.interface";

export const dummyStaff: IStaff[] = [
  {
    uuid: "1",
    name: "Andi Saputra",
    email: "andi.saputra@example.com",
    phone_number: "081234567890",
    gander: "male",
    is_active: true,
    user_type: "admin",
    profile_picture: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    uuid: "2",
    name: "Budi Santoso",
    email: "budi.santoso@example.com",
    phone_number: "081234567891",
    gander: "male",
    is_active: false,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    uuid: "3",
    name: "Citra Dewi",
    email: "citra.dewi@example.com",
    phone_number: "081234567892",
    gander: "female",
    is_active: true,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    uuid: "4",
    name: "Dewi Lestari",
    email: "dewi.lestari@example.com",
    phone_number: "081234567893",
    gander: "female",
    is_active: true,
    user_type: "admin",
    profile_picture: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    uuid: "5",
    name: "Eko Prasetyo",
    email: "eko.prasetyo@example.com",
    phone_number: "081234567894",
    gander: "male",
    is_active: false,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    uuid: "6",
    name: "Fajar Hidayat",
    email: "fajar.hidayat@example.com",
    phone_number: "081234567895",
    gander: "male",
    is_active: true,
    user_type: "admin",
    profile_picture: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    uuid: "7",
    name: "Gita Puspita",
    email: "gita.puspita@example.com",
    phone_number: "081234567896",
    gander: "female",
    is_active: true,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    uuid: "8",
    name: "Hendra Wijaya",
    email: "hendra.wijaya@example.com",
    phone_number: "081234567897",
    gander: "male",
    is_active: false,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    uuid: "9",
    name: "Indah Permata",
    email: "indah.permata@example.com",
    phone_number: "081234567898",
    gander: "female",
    is_active: true,
    user_type: "admin",
    profile_picture: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    uuid: "10",
    name: "Joko Susilo",
    email: "joko.susilo@example.com",
    phone_number: "081234567899",
    gander: "male",
    is_active: true,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    uuid: "11",
    name: "Kiki Amelia",
    email: "kiki.amelia@example.com",
    phone_number: "081234567800",
    gander: "female",
    is_active: false,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    uuid: "12",
    name: "Lina Marlina",
    email: "lina.marlina@example.com",
    phone_number: "081234567801",
    gander: "female",
    is_active: true,
    user_type: "admin",
    profile_picture: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    uuid: "13",
    name: "Maman Suryaman",
    email: "maman.suryaman@example.com",
    phone_number: "081234567802",
    gander: "male",
    is_active: true,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    uuid: "14",
    name: "Nina Kartika",
    email: "nina.kartika@example.com",
    phone_number: "081234567803",
    gander: "female",
    is_active: false,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    uuid: "15",
    name: "Oki Setiawan",
    email: "oki.setiawan@example.com",
    phone_number: "081234567804",
    gander: "male",
    is_active: true,
    user_type: "admin",
    profile_picture: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    uuid: "16",
    name: "Putri Ayu",
    email: "putri.ayu@example.com",
    phone_number: "081234567805",
    gander: "female",
    is_active: true,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    uuid: "17",
    name: "Qori Rahman",
    email: "qori.rahman@example.com",
    phone_number: "081234567806",
    gander: "male",
    is_active: false,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    uuid: "18",
    name: "Rina Sari",
    email: "rina.sari@example.com",
    phone_number: "081234567807",
    gander: "female",
    is_active: true,
    user_type: "admin",
    profile_picture: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    uuid: "19",
    name: "Sigit Nugroho",
    email: "sigit.nugroho@example.com",
    phone_number: "081234567808",
    gander: "male",
    is_active: true,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    uuid: "20",
    name: "Tina Melati",
    email: "tina.melati@example.com",
    phone_number: "081234567809",
    gander: "female",
    is_active: false,
    user_type: "staff",
    profile_picture: "https://randomuser.me/api/portraits/women/20.jpg",
  },
];