import { IBankSoal } from "./bank-soal.interface";

export const dummyBankSoal: IBankSoal[] = [
  {
    id: "1",
    title: "Soal Matematika Dasar",
    desc: "Kumpulan soal aritmatika dasar untuk siswa kelas 4–6.",
    tag: [
      { name: "Matematika", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Mudah", type: "Kesulitan" },
      { name: "Dipilih 150x", type: "Statistik" },
      { name: "Aritmatika", type: "Topik" },
      { name: "Level SD", type: "Level" },
    ],
  },
  {
    id: "2",
    title: "Pemahaman Teks Bacaan",
    desc: "Evaluasi kemampuan membaca dan memahami bacaan pendek.",
    tag: [
      { name: "Bahasa Indonesia", type: "Kategori" },
      { name: "Essay", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 88x", type: "Statistik" },
      { name: "Reading", type: "Topik" },
      { name: "Kelas 6", type: "Level" },
    ],
  },
  {
    id: "3",
    title: "Soal IPA: Sistem Pencernaan",
    desc: "Latihan soal seputar sistem pencernaan pada manusia.",
    tag: [
      { name: "IPA", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Mudah", type: "Kesulitan" },
      { name: "Dipilih 98x", type: "Statistik" },
      { name: "Biologi", type: "Topik" },
      { name: "SMP", type: "Level" },
    ],
  },
  {
    id: "4",
    title: "Logika dan Penalaran",
    desc: "Tes logika dasar dan kemampuan penalaran matematis.",
    tag: [
      { name: "Logika", type: "Kategori" },
      { name: "Essay", type: "Tipe" },
      { name: "Sulit", type: "Kesulitan" },
      { name: "Dipilih 65x", type: "Statistik" },
      { name: "Logika Matematika", type: "Topik" },
      { name: "Level SMA", type: "Level" },
    ],
  },
  {
    id: "5",
    title: "Soal Sejarah Indonesia",
    desc: "Menguji pengetahuan tentang masa kemerdekaan RI.",
    tag: [
      { name: "Sejarah", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 105x", type: "Statistik" },
      { name: "Kemerdekaan", type: "Topik" },
      { name: "Sumber Nasional", type: "Sumber" },
    ],
  },
  {
    id: "6",
    title: "Soal Fisika: Gaya & Gerak",
    desc: "Pertanyaan dasar tentang hukum Newton dan gaya.",
    tag: [
      { name: "Fisika", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 77x", type: "Statistik" },
      { name: "Gerak", type: "Topik" },
      { name: "Level SMP", type: "Level" },
    ],
  },
  {
    id: "7",
    title: "Soal Matematika Dasar",
    desc: "Kumpulan soal aritmatika dasar untuk siswa kelas 4–6.",
    tag: [
      { name: "Matematika", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Mudah", type: "Kesulitan" },
      { name: "Dipilih 150x", type: "Statistik" },
      { name: "Aritmatika", type: "Topik" },
      { name: "Level SD", type: "Level" },
    ],
  },
  {
    id: "8",
    title: "Pemahaman Teks Bacaan",
    desc: "Evaluasi kemampuan membaca dan memahami bacaan pendek.",
    tag: [
      { name: "Bahasa Indonesia", type: "Kategori" },
      { name: "Essay", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 88x", type: "Statistik" },
      { name: "Reading", type: "Topik" },
      { name: "Kelas 6", type: "Level" },
    ],
  },
  {
    id: "9",
    title: "Soal IPA: Sistem Pencernaan",
    desc: "Latihan soal seputar sistem pencernaan pada manusia.",
    tag: [
      { name: "IPA", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Mudah", type: "Kesulitan" },
      { name: "Dipilih 98x", type: "Statistik" },
      { name: "Biologi", type: "Topik" },
      { name: "SMP", type: "Level" },
    ],
  },
  {
    id: "10",
    title: "Logika dan Penalaran",
    desc: "Tes logika dasar dan kemampuan penalaran matematis.",
    tag: [
      { name: "Logika", type: "Kategori" },
      { name: "Essay", type: "Tipe" },
      { name: "Sulit", type: "Kesulitan" },
      { name: "Dipilih 65x", type: "Statistik" },
      { name: "Logika Matematika", type: "Topik" },
      { name: "Level SMA", type: "Level" },
    ],
  },
  {
    id: "11",
    title: "Soal Sejarah Indonesia",
    desc: "Menguji pengetahuan tentang masa kemerdekaan RI.",
    tag: [
      { name: "Sejarah", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 105x", type: "Statistik" },
      { name: "Kemerdekaan", type: "Topik" },
      { name: "Sumber Nasional", type: "Sumber" },
    ],
  },
  {
    id: "12",
    title: "Soal Fisika: Gaya & Gerak",
    desc: "Pertanyaan dasar tentang hukum Newton dan gaya.",
    tag: [
      { name: "Fisika", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 77x", type: "Statistik" },
      { name: "Gerak", type: "Topik" },
      { name: "Level SMP", type: "Level" },
    ],
  },
  {
    id: "13",
    title: "Soal Matematika Dasar",
    desc: "Kumpulan soal aritmatika dasar untuk siswa kelas 4–6.",
    tag: [
      { name: "Matematika", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Mudah", type: "Kesulitan" },
      { name: "Dipilih 150x", type: "Statistik" },
      { name: "Aritmatika", type: "Topik" },
      { name: "Level SD", type: "Level" },
    ],
  },
  {
    id: "14",
    title: "Pemahaman Teks Bacaan",
    desc: "Evaluasi kemampuan membaca dan memahami bacaan pendek.",
    tag: [
      { name: "Bahasa Indonesia", type: "Kategori" },
      { name: "Essay", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 88x", type: "Statistik" },
      { name: "Reading", type: "Topik" },
      { name: "Kelas 6", type: "Level" },
    ],
  },
  {
    id: "15",
    title: "Soal IPA: Sistem Pencernaan",
    desc: "Latihan soal seputar sistem pencernaan pada manusia.",
    tag: [
      { name: "IPA", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Mudah", type: "Kesulitan" },
      { name: "Dipilih 98x", type: "Statistik" },
      { name: "Biologi", type: "Topik" },
      { name: "SMP", type: "Level" },
    ],
  },
  {
    id: "16",
    title: "Logika dan Penalaran",
    desc: "Tes logika dasar dan kemampuan penalaran matematis.",
    tag: [
      { name: "Logika", type: "Kategori" },
      { name: "Essay", type: "Tipe" },
      { name: "Sulit", type: "Kesulitan" },
      { name: "Dipilih 65x", type: "Statistik" },
      { name: "Logika Matematika", type: "Topik" },
      { name: "Level SMA", type: "Level" },
    ],
  },
  {
    id: "17",
    title: "Soal Sejarah Indonesia",
    desc: "Menguji pengetahuan tentang masa kemerdekaan RI.",
    tag: [
      { name: "Sejarah", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 105x", type: "Statistik" },
      { name: "Kemerdekaan", type: "Topik" },
      { name: "Sumber Nasional", type: "Sumber" },
    ],
  },
  {
    id: "18",
    title: "Soal Fisika: Gaya & Gerak",
    desc: "Pertanyaan dasar tentang hukum Newton dan gaya.",
    tag: [
      { name: "Fisika", type: "Kategori" },
      { name: "Pilihan Ganda", type: "Tipe" },
      { name: "Sedang", type: "Kesulitan" },
      { name: "Dipilih 77x", type: "Statistik" },
      { name: "Gerak", type: "Topik" },
      { name: "Level SMP", type: "Level" },
    ],
  },
];
